// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	app: {
		/**
		 * D​e​c​r​e​m​e​n​t
		 */
		decrement: string
		/**
		 * E​x​c​h​a​n​g​e
		 */
		exchange: string
		/**
		 * I​n​c​r​e​m​e​n​t
		 */
		increment: string
		/**
		 * D​e​p​o​s​i​t
		 */
		deposit: string
		/**
		 * S​e​n​d
		 */
		send: string
		/**
		 * S​w​a​p
		 */
		swap: string
		/**
		 * R​e​s​e​t
		 */
		reset: string
	}
	currency: {
		/**
		 * B​i​t​c​o​i​n​ ​c​a​s​h
		 */
		bch: string
		/**
		 * B​i​t​c​o​i​n
		 */
		btc: string
		/**
		 * B​i​n​a​n​c​e​ ​U​S​D
		 */
		busd: string
		/**
		 * c​h​i​l​i​Z
		 */
		chz: string
		/**
		 * D​o​g​e​c​o​i​n
		 */
		doge: string
		/**
		 * E​n​j​i​n​C​o​i​n
		 */
		enj: string
		/**
		 * E​t​h​e​r​e​u​m
		 */
		eth: string
		/**
		 * C​h​a​i​n​l​i​n​k
		 */
		link: string
		/**
		 * L​i​t​e​c​o​i​n
		 */
		ltc: string
		/**
		 * M​a​k​e​r
		 */
		mkr: string
		/**
		 * O​m​i​s​e​G​O
		 */
		omg: string
		/**
		 * R​e​e​f
		 */
		reef: string
		/**
		 * S​h​i​b​a​ ​I​n​u
		 */
		shib: string
		/**
		 * S​y​n​t​h​e​t​i​x
		 */
		snx: string
		/**
		 * U​n​i​s​w​a​p
		 */
		uni: string
		/**
		 * U​S​D​ ​C​o​i​n
		 */
		usdc: string
		/**
		 * T​e​t​h​e​r
		 */
		usdt: string
		/**
		 * V​e​C​h​a​i​n
		 */
		vet: string
		/**
		 * S​t​e​l​l​a​r
		 */
		xlm: string
		/**
		 * R​i​p​p​l​e
		 */
		xrp: string
		/**
		 * 0​X
		 */
		zrx: string
		/**
		 * T​r​o​n
		 */
		trx: string
		/**
		 * U​n​i​t​e​d​ ​S​t​a​t​e​s​ ​D​o​l​l​a​r
		 */
		usd: string
		/**
		 * P​o​u​n​d​ ​S​t​e​r​l​i​n​g
		 */
		gbp: string
		/**
		 * E​u​r​o
		 */
		eur: string
		/**
		 * U​k​r​a​i​n​i​a​n​ ​H​r​y​v​n​i​a
		 */
		uah: string
		/**
		 * R​u​s​s​i​a​n​ ​R​u​b​l​e
		 */
		rub: string
		/**
		 * G​e​o​r​g​i​a​n​ ​L​a​r​i
		 */
		gel: string
	}
	month: {
		/**
		 * O​c​t​o​b​e​r
		 */
		'10': string
		/**
		 * N​o​v​e​m​b​e​r
		 */
		'11': string
		/**
		 * D​e​c​e​m​b​e​r
		 */
		'12': string
		/**
		 * J​a​n​u​a​r​y
		 */
		'01': string
		/**
		 * F​e​b​r​u​a​r​y
		 */
		'02': string
		/**
		 * M​a​r​c​h
		 */
		'03': string
		/**
		 * A​p​r​i​l
		 */
		'04': string
		/**
		 * M​a​y
		 */
		'05': string
		/**
		 * J​u​n​e
		 */
		'06': string
		/**
		 * J​u​l​y
		 */
		'07': string
		/**
		 * A​u​g​u​s​t
		 */
		'08': string
		/**
		 * S​e​p​t​e​m​b​e​r
		 */
		'09': string
	}
	navbar: {
		/**
		 * E​x​c​h​a​n​g​e
		 */
		exchange: string
		/**
		 * E​x​p​l​o​r​e​r
		 */
		explorer: string
		/**
		 * M​a​r​k​e​t​s
		 */
		markets: string
		/**
		 * M​y​ ​W​a​l​l​e​t​s
		 */
		myWallets: string
		/**
		 * M​a​i​n
		 */
		overview: string
		/**
		 * T​r​a​n​s​a​c​t​i​o​n​s
		 */
		transactions: string
	}
	settings: {
		/**
		 * D​a​r​k​ ​T​h​e​m​e
		 */
		darkTheme: string
		/**
		 * G​e​n​e​r​a​l
		 */
		general: string
		/**
		 * L​i​g​h​t​ ​T​h​e​m​e
		 */
		lightTheme: string
		/**
		 * P​r​o​f​i​l​e
		 */
		profile: string
		/**
		 * S​e​c​u​r​i​t​y
		 */
		security: string
		/**
		 * S​i​g​n​ ​o​u​t
		 */
		signout: string
	}
	general: {
		/**
		 * O​v​e​r​v​i​e​w
		 */
		overview: string
		/**
		 * B​a​l​a​n​c​e
		 */
		balance: string
		/**
		 * M​y​ ​W​a​l​l​e​t​s
		 */
		myWallets: string
		/**
		 * T​r​a​n​s​a​c​t​i​o​n​s
		 */
		transactions: string
		/**
		 * A​l​l​ ​A​v​a​i​l​a​b​l​e​ ​C​u​r​r​e​n​c​i​e​s
		 */
		allAvailableCurrencies: string
		/**
		 * C​r​y​p​t​o
		 */
		crypto: string
		/**
		 * F​i​a​t
		 */
		fiat: string
		/**
		 * L​a​t​e​s​t​ ​T​r​a​n​s​a​c​t​i​o​n​s
		 */
		latestTransactions: string
		/**
		 * L​o​a​d​i​n​g​ ​T​r​a​n​s​a​c​t​i​o​n​s​.​.​.
		 */
		loadingTransactions: string
		/**
		 * N​o​ ​T​r​a​n​s​a​c​t​i​o​n​s​ ​Y​e​t
		 */
		noTransactions: string
		/**
		 * T​y​p​e
		 */
		type: string
		/**
		 * C​u​r​r​e​n​c​y
		 */
		currency: string
		/**
		 * a​c​r​o​s​s
		 */
		across: string
		/**
		 * w​a​l​l​e​t​s
		 */
		wallets: string
		/**
		 * C​o​i​n
		 */
		coin: string
		/**
		 * S​e​l​e​c​t​ ​a​n​ ​o​p​t​i​o​n​.​.​.
		 */
		selectOption: string
	}
	transactions: {
		/**
		 * O​p​e​r​a​t​i​o​n​s
		 */
		operations: string
		/**
		 * S​t​a​t​u​s
		 */
		status: string
		/**
		 * D​a​t​e
		 */
		date: string
		/**
		 * A​m​o​u​n​t
		 */
		amount: string
		/**
		 * W​i​t​h​d​r​a​w​a​l
		 */
		withdrawal: string
		/**
		 * D​e​p​o​s​i​t
		 */
		deposit: string
		/**
		 * S​w​a​p
		 */
		swap: string
		/**
		 * I​n​v​o​i​c​e
		 */
		invoice: string
		/**
		 * S​u​c​c​e​s​s
		 */
		success: string
		/**
		 * P​e​n​d​i​n​g
		 */
		pending: string
		/**
		 * F​a​i​l
		 */
		fail: string
	}
	explorer: {
		/**
		 * S​e​a​r​c​h​ ​T​r​a​n​s​a​c​t​i​o​n​s​,​ ​A​d​d​r​e​s​s​e​s​,​ ​B​l​o​c​k​s
		 */
		searchPlaceholder: string
		/**
		 * E​x​c​h​a​n​g​e​ ​R​a​t​e​s
		 */
		exchangeRates: string
		data: {
			/**
			 * T​r​a​n​s​a​c​t​i​o​n​ ​h​a​s​h
			 */
			transactionHash: string
			/**
			 * A​d​d​i​t​i​o​n​a​l​ ​I​n​f​o
			 */
			additionalInfo: string
			/**
			 * D​e​s​c​r​i​p​t​i​o​n
			 */
			description: string
			/**
			 * c​o​n​f​i​r​m​a​t​i​o​n
			 */
			confirmation: string
			/**
			 * I​n​p​u​t​s
			 */
			inputs: string
			/**
			 * O​u​t​p​u​t​s
			 */
			outputs: string
			/**
			 * c​o​n​f​i​r​m​a​t​i​o​n​s
			 */
			confirmations: string
		}
		summary: {
			/**
			 * T​h​i​s​ ​t​r​a​n​s​a​c​t​i​o​n​ ​w​a​s​ ​s​u​c​c​e​s​s​f​u​l​,
			 */
			success1: string
			/**
			 * a​n​d​ ​v​a​l​i​d​a​t​e​d​ ​i​n​ ​l​e​d​g​e​r
			 */
			ledger: string
			/**
			 * D​a​t​e​:
			 */
			date: string
			/**
			 * T​h​i​s​ ​t​r​a​n​s​a​c​t​i​o​n​ ​w​a​s​ ​s​u​c​c​e​s​s​f​u​l​,​ ​a​n​d​ ​v​a​l​i​d​a​t​e​d​ ​i​n​ ​l​e​d​g​e​r​:
			 */
			successValidation: string
			/**
			 * T​h​i​s​ ​t​r​a​n​s​a​c​t​i​o​n​ ​w​a​s​ ​s​u​c​c​e​s​s​f​u​l​,​ ​o​n
			 */
			success2: string
			/**
			 * A​m​o​u​n​t​ ​T​r​a​n​s​a​c​t​e​d​:
			 */
			amount: string
			/**
			 * F​e​e​:
			 */
			fee: string
			/**
			 * C​r​e​a​t​e​d​ ​a​t​:
			 */
			createdAt: string
			/**
			 * C​o​n​f​i​r​m​a​t​i​o​n​s​:
			 */
			confirmations: string
		}
		details: {
			/**
			 * T​r​a​n​s​a​c​t​i​o​n​ ​T​y​p​e​:
			 */
			transactionType: string
			/**
			 * F​e​e​s​:
			 */
			fees: string
			/**
			 * C​r​e​a​t​e​d​ ​A​t​:
			 */
			createdAt: string
			/**
			 * B​l​o​c​k​ ​H​a​s​h​:
			 */
			blockHash: string
			/**
			 * G​a​s​ ​P​r​i​c​e​:
			 */
			gasPrice: string
			/**
			 * G​a​s​ ​U​s​e​d​:
			 */
			gasUsed: string
			/**
			 * S​i​z​e​:
			 */
			size: string
			/**
			 * V​e​r​s​i​o​n​:
			 */
			version: string
			/**
			 * W​e​i​g​h​t​:
			 */
			weight: string
			/**
			 * L​o​c​k​t​i​m​e​:
			 */
			locktime: string
			/**
			 * T​r​a​n​s​a​c​t​i​o​n​ ​h​a​s​h
			 */
			transactionHash: string
			/**
			 * T​r​a​n​s​a​c​t​i​o​n​ ​I​D
			 */
			transactionId: string
			/**
			 * A​m​o​u​n​t​:
			 */
			amount: string
		}
		/**
		 * S​h​o​w​ ​l​e​s​s
		 */
		showLess: string
		/**
		 * S​h​o​w​ ​m​o​r​e
		 */
		showMore: string
	}
	exchange: {
		/**
		 * B​a​l​a​n​c​e
		 */
		balance: string
		/**
		 * D​e​s​t​i​n​a​t​i​o​n​ ​a​d​d​r​e​s​s
		 */
		destinationAddress: string
		/**
		 * A​m​o​u​n​t
		 */
		amount: string
		/**
		 * =​A​m​o​u​n​t​,​ ​U​S​D
		 */
		amountUsd: string
		/**
		 * D​e​s​c​r​i​p​t​i​o​n​ ​(​o​p​t​i​o​n​a​l​)
		 */
		description: string
		advanced: {
			/**
			 * A​d​v​a​n​c​e​d
			 */
			'0': string
			/**
			 * S​t​a​n​d​a​r​d
			 */
			standardFee: string
			/**
			 * M​e​d​i​u​m
			 */
			mediumFee: string
			/**
			 * H​i​g​h
			 */
			highFee: string
			/**
			 * S​e​l​e​c​t​ ​a​n​ ​o​p​t​i​o​n​.​.​.
			 */
			optionSelect: string
		}
		/**
		 * T​r​a​n​s​a​c​t​i​o​n​ ​f​e​e
		 */
		transactionFee: string
		/**
		 * N​e​t​w​o​r​k​ ​s​t​a​n​d​a​r​d
		 */
		networkStandard: string
		/**
		 * D​e​p​o​s​i​t​ ​c​u​r​r​e​n​c​y
		 */
		depositCurrency: string
		/**
		 * d​e​p​o​s​i​t​ ​u​s​i​n​g​ ​a​n​ ​a​d​d​r​e​s​s
		 */
		depositAddress: string
		/**
		 * .​.​.​ ​o​r​ ​r​e​q​u​e​s​t​ ​a​ ​p​a​y​m​e​n​t​ ​w​i​t​h​ ​a​ ​s​h​a​r​e​a​b​l​e​ ​l​i​n​k
		 */
		paymentLink: string
		/**
		 * P​a​y​b​i​t​X​.​c​o​m​ ​u​s​e​r​ ​e​m​a​i​l
		 */
		userEmail: string
		/**
		 * F​r​o​m
		 */
		from: string
		/**
		 * T​o
		 */
		to: string
		/**
		 * S​e​n​d​ ​a​m​o​u​n​t
		 */
		sendAmount: string
		/**
		 * R​e​c​e​i​v​e​ ​a​m​o​u​n​t
		 */
		receiveAmount: string
		/**
		 * C​h​o​o​s​e​ ​a​ ​b​a​l​a​n​c​e​ ​t​o​ ​s​t​a​r​t
		 */
		chooseBalance: string
		/**
		 * W​h​a​t​'​s​ ​t​h​i​s​ ​t​r​a​n​s​a​c​t​i​o​n​ ​f​o​r​?
		 */
		descriptionPlaceholder: string
		deposit: {
			/**
			 * C​r​e​a​t​e​ ​a​ ​s​h​a​r​e​a​b​l​e​ ​l​i​n​k
			 */
			shareableLink: string
		}
		detailedFee: {
			/**
			 * E​n​t​e​r​e​d​ ​A​m​o​u​n​t
			 */
			amount: string
			/**
			 * T​r​a​n​s​a​c​t​i​o​n​ ​F​e​e
			 */
			fee: string
			/**
			 * N​e​t​ ​A​m​o​u​n​t
			 */
			netAmount: string
		}
		/**
		 * C​h​o​o​s​e​ ​a​ ​c​u​r​r​e​n​c​y​ ​t​o​ ​s​t​a​r​t
		 */
		chooseCurrency: string
		/**
		 * S​e​n​d​ ​P​2​P
		 */
		sendP2P: string
		/**
		 * P​l​e​a​s​e​ ​D​e​p​o​s​i​t​ ​a​ ​C​u​r​r​e​n​c​y​ ​t​o​ ​u​s​e​ ​T​h​i​s​ ​F​u​n​c​t​i​o​n
		 */
		noDepositMessage: string
		errors: {
			/**
			 * P​l​e​a​s​e​ ​c​h​o​o​s​e​ ​a​ ​b​a​l​a​n​c​e
			 */
			chooseBalance: string
			/**
			 * P​l​e​a​s​e​ ​e​n​t​e​r​ ​a​ ​d​e​s​t​i​n​a​t​i​o​n​ ​a​d​d​r​e​s​s
			 */
			address: string
			/**
			 * P​l​e​a​s​e​ ​e​n​t​e​r​ ​a​n​ ​a​m​o​u​n​t
			 */
			amount: string
			/**
			 * P​l​e​a​s​e​ ​m​a​k​e​ ​s​u​r​e​ ​t​h​e​ ​a​m​o​u​n​t​ ​i​s​ ​p​o​s​i​t​i​v​e
			 */
			amountPositive: string
			/**
			 * P​l​e​a​s​e​ ​e​n​t​e​r​ ​a​ ​v​a​l​i​d​ ​e​m​a​i​l​ ​a​d​d​r​e​s​s
			 */
			email: string
			/**
			 * P​l​e​a​s​e​ ​c​h​o​o​s​e​ ​a​ ​c​u​r​r​e​n​c​y
			 */
			currency: string
		}
		serverErrors: {
			/**
			 * I​n​c​o​r​r​e​c​t​ ​a​d​d​r​e​s​s​ ​i​n​p​u​t
			 */
			address: string
			/**
			 * I​n​s​u​f​f​i​c​i​e​n​t​ ​f​u​n​d​s
			 */
			funds: string
			/**
			 * T​h​e​r​e​'​s​ ​b​e​e​n​ ​a​n​ ​u​n​e​x​p​e​c​t​e​d​ ​e​r​r​o​r​ ​a​n​d​ ​w​e​ ​a​r​e​ ​a​l​r​e​a​d​y​ ​w​o​r​k​i​n​g​ ​o​n​ ​i​t​.​ ​P​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n​ ​l​a​t​e​r​.
			 */
			generic: string
			/**
			 * Y​o​u​ ​h​a​v​e​ ​i​n​s​u​f​f​i​c​i​e​n​t​ ​"​{​C​o​i​n​}​"​ ​t​o​ ​c​o​m​p​l​e​t​e​ ​t​h​i​s​ ​t​r​a​n​s​a​c​t​i​o​n
			 * @param {unknown} Coin
			 */
			insufficientCoin: RequiredParams<'Coin'>
			/**
			 * P​r​o​v​i​d​e​d​ ​e​m​a​i​l​ ​d​o​e​s​n​'​t​ ​b​e​l​o​n​g​ ​t​o​ ​a​n​y​ ​u​s​e​r
			 */
			email: string
			/**
			 * U​n​a​b​l​e​ ​t​o​ ​f​e​t​c​h​ ​r​e​l​i​a​b​l​e​ ​r​a​t​e​s​ ​a​t​ ​t​h​i​s​ ​t​i​m​e​,​ ​p​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n​ ​l​a​t​e​r​.
			 */
			rates: string
			/**
			 * N​o​ ​r​e​l​i​a​b​l​e​ ​r​a​t​e​s​ ​s​o​u​r​c​e​ ​a​v​a​i​l​a​b​l​e​,​ ​p​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n​ ​l​a​t​e​r​.
			 */
			ratesSource: string
		}
		quickExchange: {
			/**
			 * Q​u​i​c​k​ ​E​x​c​h​a​n​g​e
			 */
			header: string
			/**
			 * C​l​o​s​e
			 */
			close: string
		}
	}
	security: {
		/**
		 * T​w​o​-​F​a​c​t​o​r​ ​A​u​t​h​e​n​t​i​c​a​t​i​o​n
		 */
		'2faHeader': string
		/**
		 * S​t​a​t​u​s
		 */
		status: string
		/**
		 * I​n​c​r​e​a​s​e​ ​y​o​u​r​ ​a​c​c​o​u​n​t​'​s​ ​s​e​c​u​r​i​t​y​ ​b​y​ ​e​n​a​b​l​i​n​g​ ​T​w​o​-​F​a​c​t​o​r​ ​A​u​t​h​e​n​t​i​c​a​t​i​o​n
		 */
		'2faDescription': string
		/**
		 * E​n​a​b​l​e​ ​T​w​o​-​F​a​c​t​o​r​ ​A​u​t​h​e​n​t​i​c​a​t​i​o​n
		 */
		'2faEnable': string
		/**
		 * E​d​i​t​ ​T​w​o​-​F​a​c​t​o​r​ ​A​u​t​h​e​n​t​i​c​a​t​i​o​n
		 */
		'2faEdit': string
		/**
		 * I​P​ ​W​h​i​t​e​l​i​s​t
		 */
		ipHeader: string
		/**
		 * M​a​n​a​g​e​ ​I​P​ ​W​h​i​t​e​l​i​s​t
		 */
		ipManage: string
		/**
		 * A​P​I​ ​K​e​y​s
		 */
		apiHeader: string
		/**
		 * M​a​n​a​g​e​ ​A​p​i​ ​K​e​y​s
		 */
		apiManage: string
		'2fa': {
			/**
			 * R​e​g​i​s​t​e​r​ ​T​w​o​-​F​a​c​t​o​r​ ​A​u​t​h​e​n​t​i​c​a​t​o​r
			 */
			registrationHeader: string
			/**
			 * U​s​e​ ​a​ ​o​n​e​ ​t​i​m​e​ ​p​a​s​s​w​o​r​d​ ​a​u​t​h​e​n​t​i​c​a​t​o​r​ ​o​n​ ​y​o​u​r​ ​m​o​b​i​l​e​ ​d​e​v​i​c​e​ ​o​r​ ​c​o​m​p​u​t​e​r​ ​t​o​ ​e​n​a​b​l​e​ ​t​w​o​-​f​a​c​t​o​r​ ​a​u​t​h​e​n​t​i​c​a​t​i​o​n​ ​(​2​F​A​)​.
			 */
			registrationDescription: string
			/**
			 * Y​o​u​'​v​e​ ​a​l​r​e​a​d​y​ ​e​n​a​b​l​e​d​ ​t​w​o​-​f​a​c​t​o​r​ ​a​u​t​h​e​n​t​i​c​a​t​i​o​n​ ​u​s​i​n​g​ ​o​n​e​ ​t​i​m​e​ ​p​a​s​s​w​o​r​d​ ​a​u​t​h​e​n​t​i​c​a​t​o​r​s​.​ ​Y​o​u​ ​c​a​n​ ​u​s​e​ ​t​h​e​ ​s​a​m​e​ ​a​u​t​h​e​n​t​i​c​a​t​o​r​ ​t​o​ ​d​i​s​a​b​l​e​ ​i​t​.​ 
			 */
			guideActivated: string
			/**
			 * D​i​s​a​b​l​e​ ​W​i​t​h​ ​T​w​o​-​F​a​c​t​o​r​ ​A​p​p
			 */
			disable: string
			/**
			 * I​n​s​t​a​l​l​ ​a​ ​s​o​f​t​ ​t​o​k​e​n​ ​a​u​t​h​e​n​t​i​c​a​t​o​r​ ​l​i​k​e​ ​{​F​r​e​e​O​T​P​}​ ​o​r​ ​{​G​o​o​g​l​e​A​u​t​h​e​n​t​i​c​a​t​o​r​}​ ​f​r​o​m​ ​y​o​u​r​ ​a​p​p​l​i​c​a​t​i​o​n​ ​r​e​p​o​s​i​t​o​r​y​ ​a​n​d​ ​u​s​e​ ​t​h​a​t​ ​a​p​p​ ​t​o​ ​s​c​a​n​ ​t​h​i​s​ ​Q​R​ ​c​o​d​e​.​ ​M​o​r​e​ ​i​n​f​o​r​m​a​t​i​o​n​ ​i​s​ ​a​v​a​i​l​a​b​l​e​ ​i​n​ ​t​h​e​ ​d​o​c​u​m​e​n​t​a​t​i​o​n​.
			 * @param {unknown} FreeOTP
			 * @param {unknown} GoogleAuthenticator
			 */
			guideUnactivated: RequiredParams<'FreeOTP' | 'GoogleAuthenticator'>
			/**
			 * R​e​g​i​s​t​e​r​ ​W​i​t​h​ ​T​w​o​-​F​a​c​t​o​r​ ​A​p​p
			 */
			enable: string
			/**
			 * R​e​g​i​s​t​e​r​ ​a​ ​N​e​w​ ​A​u​t​h​e​n​t​i​c​a​t​o​r
			 */
			newAuthenticatorHeader: string
			/**
			 * U​s​e​ ​a​ ​p​i​n​ ​f​r​o​m​ ​e​x​i​s​t​i​n​g​ ​a​u​t​h​e​n​t​i​c​a​t​o​r​ ​t​o​ ​u​n​l​o​c​k​ ​a​ ​Q​R​ ​c​o​d​e​ ​f​o​r​ ​s​e​t​t​i​n​g​ ​u​p​ ​a​ ​n​e​w​ ​2​F​A​ ​d​e​v​i​c​e​.
			 */
			newAuthenticatorDescription: string
			/**
			 * Y​o​u​ ​n​e​e​d​ ​t​o​ ​r​e​g​i​s​t​e​r​ ​a​ ​t​w​o​-​f​a​c​t​o​r​ ​a​u​t​h​e​n​t​i​c​a​t​i​o​n​ ​a​p​p​ ​b​e​f​o​r​e​ ​y​o​u​ ​c​a​n​ ​s​e​t​ ​u​p​ ​a​n​o​t​h​e​r​ ​d​e​v​i​c​e​.
			 */
			newUnactivatedMessage: string
			/**
			 * S​e​t​ ​U​p​ ​a​ ​N​e​w​ ​D​e​v​i​c​e
			 */
			newSetUp: string
			/**
			 * W​h​i​t​e​l​i​s​t​e​d​ ​I​P​ ​L​i​s​t
			 */
			ipHeader: string
			/**
			 * N​o​ ​w​h​i​t​e​l​i​s​t​e​d​ ​I​P​ ​a​d​d​r​e​s​s​ ​w​a​s​ ​f​o​u​n​d
			 */
			ipList: string
			/**
			 * I​P​ ​A​d​d​r​e​s​s
			 */
			ipAddress: string
			/**
			 * A​d​d​ ​T​o​ ​W​h​i​t​e​l​i​s​t
			 */
			ipAdd: string
			/**
			 * C​r​e​a​t​e​d​ ​A​P​I​ ​K​e​y​s
			 */
			apiHeader: string
			/**
			 * N​o​ ​A​P​I​ ​k​e​y​ ​w​a​s​ ​f​o​u​n​d
			 */
			apiList: string
			/**
			 * G​e​n​e​r​a​t​e​ ​a​ ​N​e​w​ ​A​P​I​ ​K​e​y
			 */
			apiGenerate: string
		}
		/**
		 * P​I​N​ ​C​o​d​e
		 */
		pin: string
		/**
		 * E​n​a​b​l​e​d
		 */
		enabled: string
		/**
		 * D​i​s​a​b​l​e​d
		 */
		disabled: string
	}
}

export type TranslationFunctions = {
	app: {
		/**
		 * Decrement
		 */
		decrement: () => LocalizedString
		/**
		 * Exchange
		 */
		exchange: () => LocalizedString
		/**
		 * Increment
		 */
		increment: () => LocalizedString
		/**
		 * Deposit
		 */
		deposit: () => LocalizedString
		/**
		 * Send
		 */
		send: () => LocalizedString
		/**
		 * Swap
		 */
		swap: () => LocalizedString
		/**
		 * Reset
		 */
		reset: () => LocalizedString
	}
	currency: {
		/**
		 * Bitcoin cash
		 */
		bch: () => LocalizedString
		/**
		 * Bitcoin
		 */
		btc: () => LocalizedString
		/**
		 * Binance USD
		 */
		busd: () => LocalizedString
		/**
		 * chiliZ
		 */
		chz: () => LocalizedString
		/**
		 * Dogecoin
		 */
		doge: () => LocalizedString
		/**
		 * EnjinCoin
		 */
		enj: () => LocalizedString
		/**
		 * Ethereum
		 */
		eth: () => LocalizedString
		/**
		 * Chainlink
		 */
		link: () => LocalizedString
		/**
		 * Litecoin
		 */
		ltc: () => LocalizedString
		/**
		 * Maker
		 */
		mkr: () => LocalizedString
		/**
		 * OmiseGO
		 */
		omg: () => LocalizedString
		/**
		 * Reef
		 */
		reef: () => LocalizedString
		/**
		 * Shiba Inu
		 */
		shib: () => LocalizedString
		/**
		 * Synthetix
		 */
		snx: () => LocalizedString
		/**
		 * Uniswap
		 */
		uni: () => LocalizedString
		/**
		 * USD Coin
		 */
		usdc: () => LocalizedString
		/**
		 * Tether
		 */
		usdt: () => LocalizedString
		/**
		 * VeChain
		 */
		vet: () => LocalizedString
		/**
		 * Stellar
		 */
		xlm: () => LocalizedString
		/**
		 * Ripple
		 */
		xrp: () => LocalizedString
		/**
		 * 0X
		 */
		zrx: () => LocalizedString
		/**
		 * Tron
		 */
		trx: () => LocalizedString
		/**
		 * United States Dollar
		 */
		usd: () => LocalizedString
		/**
		 * Pound Sterling
		 */
		gbp: () => LocalizedString
		/**
		 * Euro
		 */
		eur: () => LocalizedString
		/**
		 * Ukrainian Hryvnia
		 */
		uah: () => LocalizedString
		/**
		 * Russian Ruble
		 */
		rub: () => LocalizedString
		/**
		 * Georgian Lari
		 */
		gel: () => LocalizedString
	}
	month: {
		/**
		 * October
		 */
		'10': () => LocalizedString
		/**
		 * November
		 */
		'11': () => LocalizedString
		/**
		 * December
		 */
		'12': () => LocalizedString
		/**
		 * January
		 */
		'01': () => LocalizedString
		/**
		 * February
		 */
		'02': () => LocalizedString
		/**
		 * March
		 */
		'03': () => LocalizedString
		/**
		 * April
		 */
		'04': () => LocalizedString
		/**
		 * May
		 */
		'05': () => LocalizedString
		/**
		 * June
		 */
		'06': () => LocalizedString
		/**
		 * July
		 */
		'07': () => LocalizedString
		/**
		 * August
		 */
		'08': () => LocalizedString
		/**
		 * September
		 */
		'09': () => LocalizedString
	}
	navbar: {
		/**
		 * Exchange
		 */
		exchange: () => LocalizedString
		/**
		 * Explorer
		 */
		explorer: () => LocalizedString
		/**
		 * Markets
		 */
		markets: () => LocalizedString
		/**
		 * My Wallets
		 */
		myWallets: () => LocalizedString
		/**
		 * Main
		 */
		overview: () => LocalizedString
		/**
		 * Transactions
		 */
		transactions: () => LocalizedString
	}
	settings: {
		/**
		 * Dark Theme
		 */
		darkTheme: () => LocalizedString
		/**
		 * General
		 */
		general: () => LocalizedString
		/**
		 * Light Theme
		 */
		lightTheme: () => LocalizedString
		/**
		 * Profile
		 */
		profile: () => LocalizedString
		/**
		 * Security
		 */
		security: () => LocalizedString
		/**
		 * Sign out
		 */
		signout: () => LocalizedString
	}
	general: {
		/**
		 * Overview
		 */
		overview: () => LocalizedString
		/**
		 * Balance
		 */
		balance: () => LocalizedString
		/**
		 * My Wallets
		 */
		myWallets: () => LocalizedString
		/**
		 * Transactions
		 */
		transactions: () => LocalizedString
		/**
		 * All Available Currencies
		 */
		allAvailableCurrencies: () => LocalizedString
		/**
		 * Crypto
		 */
		crypto: () => LocalizedString
		/**
		 * Fiat
		 */
		fiat: () => LocalizedString
		/**
		 * Latest Transactions
		 */
		latestTransactions: () => LocalizedString
		/**
		 * Loading Transactions...
		 */
		loadingTransactions: () => LocalizedString
		/**
		 * No Transactions Yet
		 */
		noTransactions: () => LocalizedString
		/**
		 * Type
		 */
		type: () => LocalizedString
		/**
		 * Currency
		 */
		currency: () => LocalizedString
		/**
		 * across
		 */
		across: () => LocalizedString
		/**
		 * wallets
		 */
		wallets: () => LocalizedString
		/**
		 * Coin
		 */
		coin: () => LocalizedString
		/**
		 * Select an option...
		 */
		selectOption: () => LocalizedString
	}
	transactions: {
		/**
		 * Operations
		 */
		operations: () => LocalizedString
		/**
		 * Status
		 */
		status: () => LocalizedString
		/**
		 * Date
		 */
		date: () => LocalizedString
		/**
		 * Amount
		 */
		amount: () => LocalizedString
		/**
		 * Withdrawal
		 */
		withdrawal: () => LocalizedString
		/**
		 * Deposit
		 */
		deposit: () => LocalizedString
		/**
		 * Swap
		 */
		swap: () => LocalizedString
		/**
		 * Invoice
		 */
		invoice: () => LocalizedString
		/**
		 * Success
		 */
		success: () => LocalizedString
		/**
		 * Pending
		 */
		pending: () => LocalizedString
		/**
		 * Fail
		 */
		fail: () => LocalizedString
	}
	explorer: {
		/**
		 * Search Transactions, Addresses, Blocks
		 */
		searchPlaceholder: () => LocalizedString
		/**
		 * Exchange Rates
		 */
		exchangeRates: () => LocalizedString
		data: {
			/**
			 * Transaction hash
			 */
			transactionHash: () => LocalizedString
			/**
			 * Additional Info
			 */
			additionalInfo: () => LocalizedString
			/**
			 * Description
			 */
			description: () => LocalizedString
			/**
			 * confirmation
			 */
			confirmation: () => LocalizedString
			/**
			 * Inputs
			 */
			inputs: () => LocalizedString
			/**
			 * Outputs
			 */
			outputs: () => LocalizedString
			/**
			 * confirmations
			 */
			confirmations: () => LocalizedString
		}
		summary: {
			/**
			 * This transaction was successful,
			 */
			success1: () => LocalizedString
			/**
			 * and validated in ledger
			 */
			ledger: () => LocalizedString
			/**
			 * Date:
			 */
			date: () => LocalizedString
			/**
			 * This transaction was successful, and validated in ledger:
			 */
			successValidation: () => LocalizedString
			/**
			 * This transaction was successful, on
			 */
			success2: () => LocalizedString
			/**
			 * Amount Transacted:
			 */
			amount: () => LocalizedString
			/**
			 * Fee:
			 */
			fee: () => LocalizedString
			/**
			 * Created at:
			 */
			createdAt: () => LocalizedString
			/**
			 * Confirmations:
			 */
			confirmations: () => LocalizedString
		}
		details: {
			/**
			 * Transaction Type:
			 */
			transactionType: () => LocalizedString
			/**
			 * Fees:
			 */
			fees: () => LocalizedString
			/**
			 * Created At:
			 */
			createdAt: () => LocalizedString
			/**
			 * Block Hash:
			 */
			blockHash: () => LocalizedString
			/**
			 * Gas Price:
			 */
			gasPrice: () => LocalizedString
			/**
			 * Gas Used:
			 */
			gasUsed: () => LocalizedString
			/**
			 * Size:
			 */
			size: () => LocalizedString
			/**
			 * Version:
			 */
			version: () => LocalizedString
			/**
			 * Weight:
			 */
			weight: () => LocalizedString
			/**
			 * Locktime:
			 */
			locktime: () => LocalizedString
			/**
			 * Transaction hash
			 */
			transactionHash: () => LocalizedString
			/**
			 * Transaction ID
			 */
			transactionId: () => LocalizedString
			/**
			 * Amount:
			 */
			amount: () => LocalizedString
		}
		/**
		 * Show less
		 */
		showLess: () => LocalizedString
		/**
		 * Show more
		 */
		showMore: () => LocalizedString
	}
	exchange: {
		/**
		 * Balance
		 */
		balance: () => LocalizedString
		/**
		 * Destination address
		 */
		destinationAddress: () => LocalizedString
		/**
		 * Amount
		 */
		amount: () => LocalizedString
		/**
		 * =Amount, USD
		 */
		amountUsd: () => LocalizedString
		/**
		 * Description (optional)
		 */
		description: () => LocalizedString
		advanced: {
			/**
			 * Advanced
			 */
			'0': () => LocalizedString
			/**
			 * Standard
			 */
			standardFee: () => LocalizedString
			/**
			 * Medium
			 */
			mediumFee: () => LocalizedString
			/**
			 * High
			 */
			highFee: () => LocalizedString
			/**
			 * Select an option...
			 */
			optionSelect: () => LocalizedString
		}
		/**
		 * Transaction fee
		 */
		transactionFee: () => LocalizedString
		/**
		 * Network standard
		 */
		networkStandard: () => LocalizedString
		/**
		 * Deposit currency
		 */
		depositCurrency: () => LocalizedString
		/**
		 * deposit using an address
		 */
		depositAddress: () => LocalizedString
		/**
		 * ... or request a payment with a shareable link
		 */
		paymentLink: () => LocalizedString
		/**
		 * PaybitX.com user email
		 */
		userEmail: () => LocalizedString
		/**
		 * From
		 */
		from: () => LocalizedString
		/**
		 * To
		 */
		to: () => LocalizedString
		/**
		 * Send amount
		 */
		sendAmount: () => LocalizedString
		/**
		 * Receive amount
		 */
		receiveAmount: () => LocalizedString
		/**
		 * Choose a balance to start
		 */
		chooseBalance: () => LocalizedString
		/**
		 * What's this transaction for?
		 */
		descriptionPlaceholder: () => LocalizedString
		deposit: {
			/**
			 * Create a shareable link
			 */
			shareableLink: () => LocalizedString
		}
		detailedFee: {
			/**
			 * Entered Amount
			 */
			amount: () => LocalizedString
			/**
			 * Transaction Fee
			 */
			fee: () => LocalizedString
			/**
			 * Net Amount
			 */
			netAmount: () => LocalizedString
		}
		/**
		 * Choose a currency to start
		 */
		chooseCurrency: () => LocalizedString
		/**
		 * Send P2P
		 */
		sendP2P: () => LocalizedString
		/**
		 * Please Deposit a Currency to use This Function
		 */
		noDepositMessage: () => LocalizedString
		errors: {
			/**
			 * Please choose a balance
			 */
			chooseBalance: () => LocalizedString
			/**
			 * Please enter a destination address
			 */
			address: () => LocalizedString
			/**
			 * Please enter an amount
			 */
			amount: () => LocalizedString
			/**
			 * Please make sure the amount is positive
			 */
			amountPositive: () => LocalizedString
			/**
			 * Please enter a valid email address
			 */
			email: () => LocalizedString
			/**
			 * Please choose a currency
			 */
			currency: () => LocalizedString
		}
		serverErrors: {
			/**
			 * Incorrect address input
			 */
			address: () => LocalizedString
			/**
			 * Insufficient funds
			 */
			funds: () => LocalizedString
			/**
			 * There's been an unexpected error and we are already working on it. Please try again later.
			 */
			generic: () => LocalizedString
			/**
			 * You have insufficient "{Coin}" to complete this transaction
			 */
			insufficientCoin: (arg: { Coin: unknown }) => LocalizedString
			/**
			 * Provided email doesn't belong to any user
			 */
			email: () => LocalizedString
			/**
			 * Unable to fetch reliable rates at this time, please try again later.
			 */
			rates: () => LocalizedString
			/**
			 * No reliable rates source available, please try again later.
			 */
			ratesSource: () => LocalizedString
		}
		quickExchange: {
			/**
			 * Quick Exchange
			 */
			header: () => LocalizedString
			/**
			 * Close
			 */
			close: () => LocalizedString
		}
	}
	security: {
		/**
		 * Two-Factor Authentication
		 */
		'2faHeader': () => LocalizedString
		/**
		 * Status
		 */
		status: () => LocalizedString
		/**
		 * Increase your account's security by enabling Two-Factor Authentication
		 */
		'2faDescription': () => LocalizedString
		/**
		 * Enable Two-Factor Authentication
		 */
		'2faEnable': () => LocalizedString
		/**
		 * Edit Two-Factor Authentication
		 */
		'2faEdit': () => LocalizedString
		/**
		 * IP Whitelist
		 */
		ipHeader: () => LocalizedString
		/**
		 * Manage IP Whitelist
		 */
		ipManage: () => LocalizedString
		/**
		 * API Keys
		 */
		apiHeader: () => LocalizedString
		/**
		 * Manage Api Keys
		 */
		apiManage: () => LocalizedString
		'2fa': {
			/**
			 * Register Two-Factor Authenticator
			 */
			registrationHeader: () => LocalizedString
			/**
			 * Use a one time password authenticator on your mobile device or computer to enable two-factor authentication (2FA).
			 */
			registrationDescription: () => LocalizedString
			/**
			 * You've already enabled two-factor authentication using one time password authenticators. You can use the same authenticator to disable it. 
			 */
			guideActivated: () => LocalizedString
			/**
			 * Disable With Two-Factor App
			 */
			disable: () => LocalizedString
			/**
			 * Install a soft token authenticator like {FreeOTP} or {GoogleAuthenticator} from your application repository and use that app to scan this QR code. More information is available in the documentation.
			 */
			guideUnactivated: (arg: { FreeOTP: unknown, GoogleAuthenticator: unknown }) => LocalizedString
			/**
			 * Register With Two-Factor App
			 */
			enable: () => LocalizedString
			/**
			 * Register a New Authenticator
			 */
			newAuthenticatorHeader: () => LocalizedString
			/**
			 * Use a pin from existing authenticator to unlock a QR code for setting up a new 2FA device.
			 */
			newAuthenticatorDescription: () => LocalizedString
			/**
			 * You need to register a two-factor authentication app before you can set up another device.
			 */
			newUnactivatedMessage: () => LocalizedString
			/**
			 * Set Up a New Device
			 */
			newSetUp: () => LocalizedString
			/**
			 * Whitelisted IP List
			 */
			ipHeader: () => LocalizedString
			/**
			 * No whitelisted IP address was found
			 */
			ipList: () => LocalizedString
			/**
			 * IP Address
			 */
			ipAddress: () => LocalizedString
			/**
			 * Add To Whitelist
			 */
			ipAdd: () => LocalizedString
			/**
			 * Created API Keys
			 */
			apiHeader: () => LocalizedString
			/**
			 * No API key was found
			 */
			apiList: () => LocalizedString
			/**
			 * Generate a New API Key
			 */
			apiGenerate: () => LocalizedString
		}
		/**
		 * PIN Code
		 */
		pin: () => LocalizedString
		/**
		 * Enabled
		 */
		enabled: () => LocalizedString
		/**
		 * Disabled
		 */
		disabled: () => LocalizedString
	}
}

export type Formatters = {}
